database:
  host: "172.19.16.1"
  port: 5433
  username: "postgres"
  password: "admin"
  database: "lab_inspection"

systems:
  scanControl:
    connection_type: "tcp"
    ip: "192.168.3.2"
    timeout: 30
    type: "laser_scanner"
  camera:
    connection_type: "usb"
    device_id: "Intel Corp"
    timeout: 15
    type: "camera_system"
  table:
    connection_type: "serial"
    port: "/dev/ttyUSB0"
    baudrate: 9600
    timeout: 10
    type: "rotating_table"
  gantry:
    connection_type: "tcp"
    ip: "192.168.3.11"
    port: 3920
    timeout: 20
    type: "gantry_system"

ftp:
  server: "ftp://inspection-server"
  username: "ftp_user"
  password: "ftp_password"
  base_path: "/aircraft"

output:
  base_directory: "./output"
  date_format: "%Y-%m-%d"
  time_format: "%Y-%m-%d_%H-%M-%S"

logging:
  level: "INFO"
  file: "logs/scenario_inspector.log"
  console: true

security:
  bcrypt_rounds: 12
  session_timeout: 3600  # seconds

gui:
  window_title: "AUAS Scenario Inspector"
  theme: "default"
  default_geometry: "1200x800"
