database:
  host: "172.21.240.1"
  port: 5433
  username: "postgres"
  password: "admin"
  database: "lab_inspection"

systems:
  scanControl:
    connection_type: "tcp"
    llt_path: "/home/agordien/projects/auas_inspection_engine/scanCONTROL-Linux-SDK-1-0-1/python_bindings"
    ip: "192.168.3.2"
    timeout: 30
    type: "scanner_system"
  camera:
    connection_type: "usb"
    device_id: "Intel Corp"
    timeout: 15
    type: "camera_system"
  table:
    connection_type: "serial"
    port: "/dev/ttyUSB0"
    baudrate: 9600
    timeout: 10
    type: "rotating_table"
  gantry:
    connection_type: "tcp"
    # ip: "192.168.3.11"
    ip: "172.21.240.1"
    port: 3921
    timeout: 20
    programs_path: "/home/agordien/projects/auas_inspection_engine/scenario_inspector/src/systems/gantry_programs"
    type: "gantry_system"

ftp:
  server: "ftp://inspection-server"
  username: "ftp_user"
  password: "ftp_password"
  base_path: "/aircraft"

output:
  base_directory: "./output"
  date_format: "%Y-%m-%d"
  time_format: "%Y-%m-%d_%H-%M-%S"

logging:
  level: "DEBUG"
  log_folder_path: "scenario_inspector/logs"
  log_file_prefix: "scenario_inspector"
  console: true

security:
  bcrypt_rounds: 12
  session_timeout: 3600  # seconds

gui:
  window_title: "AUAS Scenario Inspector"
  theme: "default"
  default_geometry: "1200x800"
